from __future__ import annotations

from typing import Protocol

from domain.entities.archive import Archive
from domain.entities.archive_entry import ArchiveEntry, ArchiveEntryStatus


class ArchiveRepository(Protocol):
    async def create(self, archive: Archive) -> Archive: ...

    async def get_by_id(self, archive_id: int) -> Archive | None: ...

    async def get_by_name(self, name: str) -> Archive | None: ...

    async def list(self, *, limit: int = 100, offset: int = 0) -> list[Archive]: ...

    async def count(self) -> int: ...

    async def count_downloaded(self) -> int: ...

    async def save(self, archive: Archive) -> None: ...


class ArchiveEntryRepository(Protocol):
    async def create(self, entry: ArchiveEntry) -> ArchiveEntry: ...

    async def bulk_create(self, entries: list[ArchiveEntry]) -> int: ...

    async def bulk_update_file_ids(self, entries: list[ArchiveEntry]) -> None: ...

    async def get_by_id(self, entry_id: int) -> ArchiveEntry | None: ...

    async def get_by_relative_path(self, relative_path: str) -> ArchiveEntry | None: ...

    async def get_by_logical_id(self, logical_id: str) -> ArchiveEntry | None: ...

    async def get_by_file_id(self, file_id: int) -> ArchiveEntry | None: ...

    async def list_by_archive(self, archive_id: int) -> list[ArchiveEntry]: ...

    async def list_by_work(self, work_id: int) -> list[ArchiveEntry]: ...

    async def list_by_work_ids(self, work_ids: list[int]) -> list[ArchiveEntry]: ...

    async def list_all(self, *, limit: int = 1000, offset: int = 0) -> list[ArchiveEntry]: ...

    async def bulk_update_work_ids(self, entries: list[ArchiveEntry]) -> None: ...

    async def search(self, query: str, *, limit: int = 50, offset: int = 0) -> list[ArchiveEntry]: ...

    async def list_relative_paths(self) -> list[str]: ...

    async def count_total(self) -> int: ...

    async def count_by_status(self, status: ArchiveEntryStatus) -> int: ...

    async def count_by_archive(self, archive_id: int) -> int: ...

    async def save(self, entry: ArchiveEntry) -> None: ...
