from __future__ import annotations

from typing import Protocol

from domain.entities.download_job import DownloadJob
from domain.entities.file import File
from domain.entities.storage_location import StorageLocation
from domain.entities.storage_provider import StorageProvider


class FileRepository(Protocol):
    async def create(self, file: File) -> File: ...

    async def get_by_id(self, file_id: int) -> File | None: ...

    async def get_by_sha256(self, sha256: str) -> File | None: ...

    async def save(self, file: File) -> None: ...

    async def delete(self, file_id: int) -> None: ...

    async def count(self) -> int: ...

    async def sum_size(self) -> int: ...

    async def list(self, *, limit: int = 100, offset: int = 0) -> list[File]: ...


class StorageProviderRepository(Protocol):
    async def create(self, provider: StorageProvider) -> StorageProvider: ...

    async def get_by_id(self, provider_id: int) -> StorageProvider | None: ...

    async def list(self, *, enabled_only: bool = True) -> list[StorageProvider]: ...

    async def save(self, provider: StorageProvider) -> None: ...


class StorageLocationRepository(Protocol):
    async def create(self, location: StorageLocation) -> StorageLocation: ...

    async def get_by_id(self, location_id: int) -> StorageLocation | None: ...

    async def get_by_file_and_provider(self, file_id: int, provider_id: int) -> StorageLocation | None: ...

    async def list_by_file(self, file_id: int) -> list[StorageLocation]: ...

    async def delete_by_file(self, file_id: int) -> None: ...

    async def save(self, location: StorageLocation) -> None: ...


class DownloadJobRepository(Protocol):
    async def create(self, job: DownloadJob) -> DownloadJob: ...

    async def get_by_id(self, job_id: int) -> DownloadJob | None: ...

    async def save(self, job: DownloadJob) -> None: ...

    async def list_by_file(self, file_id: int) -> list[DownloadJob]: ...
