from __future__ import annotations

from typing import Protocol

from domain.entities.work import Work, WorkLists


class WorkRepository(Protocol):
    async def create(self, work: Work) -> Work: ...

    async def update(self, work: Work) -> None: ...

    async def get_by_id(self, work_id: int) -> Work | None: ...

    async def get_by_work_key(self, work_key: str) -> Work | None: ...

    async def search(self, query: str, *, limit: int = 50, offset: int = 0) -> list[Work]: ...

    async def all_(self, *, limit: int = 100, offset: int = 0) -> list[Work]: ...

    async def list_all(self, *, limit: int = 1000, offset: int = 0) -> list[Work]: ...

    async def count(self) -> int: ...

    async def replace_tags(self, work_id: int, tags: list[str]) -> None: ...

    async def replace_genres(self, work_id: int, genres: list[str]) -> None: ...

    async def replace_instruments(self, work_id: int, instruments: list[str]) -> None: ...

    async def replace_parts(self, work_id: int, parts: list[str]) -> None: ...

    async def get_tags(self, work_id: int) -> list[str]: ...

    async def get_genres(self, work_id: int) -> list[str]: ...

    async def get_instruments(self, work_id: int) -> list[str]: ...

    async def get_parts(self, work_id: int) -> list[str]: ...

    async def get_lists_bulk(self, work_ids: list[int]) -> dict[int, WorkLists]: ...

    async def list_by_composer(
        self, composer_id: str, *, limit: int = 100, offset: int = 0
    ) -> list[Work]:
        """Works cuyo composer_id es exactamente este compositor."""

