from __future__ import annotations

from domain.entities.catalogue import Catalogue

# Catálogos temáticos por compositor. Fuente: Wikipedia (Opus (música)).
# Cada entrada: (prefijo, compositor, nombre del catálogo, creador, criterio de ordenación).
CATALOGUES = [
    Catalogue(prefix="K", composer="Wolfgang Amadeus Mozart",
              catalogue_name="Catálogo Köchel (Köchel-Verzeichnis)",
              creator="Ludwig von Köchel", ordering_criterion="Cronológico"),
    Catalogue(prefix="KV", composer="Wolfgang Amadeus Mozart",
              catalogue_name="Köchel-Verzeichnis",
              creator="Ludwig von Köchel", ordering_criterion="Cronológico"),
    Catalogue(prefix="BWV", composer="Johann Sebastian Bach",
              catalogue_name="Bach-Werke-Verzeichnis",
              creator="Wolfgang Schmieder", ordering_criterion="Temático (género)"),
    Catalogue(prefix="WoO", composer="Ludwig van Beethoven",
              catalogue_name="Werke ohne Opuszahl",
              creator="Willy Hess / Kinsky-Halm", ordering_criterion="Sin número de opus"),
    Catalogue(prefix="Hess", composer="Ludwig van Beethoven",
              catalogue_name="Catálogo Hess",
              creator="Willy Hess", ordering_criterion="Temático"),
    Catalogue(prefix="Wq", composer="Carl Philipp Emanuel Bach",
              catalogue_name="Wotquenne",
              creator="Alfred Wotquenne", ordering_criterion="Temático"),
    Catalogue(prefix="H", composer="Carl Philipp Emanuel Bach",
              catalogue_name="Helm (Thematic Catalogue of the Works of C. P. E. Bach)",
              creator="E. Eugene Helm", ordering_criterion="Temático"),
    Catalogue(prefix="Wq", composer="Christoph Willibald Gluck",
              catalogue_name="Wotquenne",
              creator="Alfred Wotquenne", ordering_criterion="Temático"),
    Catalogue(prefix="H", composer="Marc-Antoine Charpentier",
              catalogue_name="Catálogo Hitchcock",
              creator="Hugh Wiley Hitchcock", ordering_criterion="Temático"),
    Catalogue(prefix="BuxWV", composer="Dietrich Buxtehude",
              catalogue_name="Buxtehude-Werke-Verzeichnis",
              creator="Georg Karstädt", ordering_criterion="Temático"),
    Catalogue(prefix="HWV", composer="Georg Friedrich Händel",
              catalogue_name="Händel-Werke-Verzeichnis",
              creator="Bernd Baselt", ordering_criterion="Temático"),
    Catalogue(prefix="Hob", composer="Joseph Haydn",
              catalogue_name="Hoboken-Verzeichnis",
              creator="Anthony van Hoboken", ordering_criterion="Temático"),
    Catalogue(prefix="S", composer="Franz Liszt",
              catalogue_name="Catálogo Searle (The Music of Liszt)",
              creator="Humphrey Searle", ordering_criterion="Temático"),
    Catalogue(prefix="R", composer="Franz Liszt",
              catalogue_name="Catálogo Raabe (Franz Liszt: Leben und Schaffen)",
              creator="Peter Raabe", ordering_criterion="Temático"),
    Catalogue(prefix="F", composer="Wilhelm Friedemann Bach",
              catalogue_name="Catálogo Falck",
              creator="Martin Falck", ordering_criterion="Temático"),
    Catalogue(prefix="RV", composer="Antonio Vivaldi",
              catalogue_name="Ryom-Verzeichnis",
              creator="Peter Ryom", ordering_criterion="Temático"),
    Catalogue(prefix="D", composer="Franz Schubert",
              catalogue_name="Deutsch-Verzeichnis",
              creator="Otto Erich Deutsch", ordering_criterion="Cronológico"),
    Catalogue(prefix="WWV", composer="Richard Wagner",
              catalogue_name="Wagner-Werk-Verzeichnis",
              creator="Varios", ordering_criterion="Temático"),
    Catalogue(prefix="Z", composer="Henry Purcell",
              catalogue_name="Catálogo Zimmerman (Henry Purcell, 1659-1695)",
              creator="Franklin B. Zimmerman", ordering_criterion="Por tipo de composición"),
    Catalogue(prefix="L", composer="Domenico Scarlatti",
              catalogue_name="Catálogo Longo",
              creator="Alessandro Longo", ordering_criterion="Temático (piano)"),
    Catalogue(prefix="K", composer="Domenico Scarlatti",
              catalogue_name="Catálogo Kirkpatrick",
              creator="Ralph Kirkpatrick", ordering_criterion="Temático"),
    Catalogue(prefix="R", composer="Antonio Soler",
              catalogue_name="Catálogo Rubio (Samuel Rubio Calzón)",
              creator="Samuel Rubio Calzón", ordering_criterion="Temático"),
]
